### ISSUE TITLE
Some cops policies not highlighted in Sublime Text 3

### ISSUE THREAD

**Issue by kofronpi** [pderichs/sublime_rubocop#26] opened 2014-11-17 16:59 UTC
Some policies are not highlighted by sublime_rubocop.

I run Sublime Text 3 beta under ubuntu 14.04, rubocop v 0.27.1. I have no sublime_rubocop user settings and I use RVM.

Those cops are affected: 

Metrics/AbcSize  (http://www.rubydoc.info/gems/rubocop/0.27.0/RuboCop/Cop/Metrics/AbcSize)

I will update if I find more.

**Comment by pderichs** [comment] 2015-03-08 12:16
Sorry, I am not able to reproduce that. I am using ST3 on Ubuntu 14.04 with rvm (rubocop version 0.29.1). Metrics/AbcSize is marked as expected.

Can you provide more details?

**Closed** 2015-04-12 09:30 UTC
